### ISSUE TITLE
合作交流和共同开发

### ISSUE THREAD

**Issue by ChenxuJWang** [ahui2016/iPelago-Server#1]
首先抱歉建了一个并不是issue的issue。我通过V2EX 您的话题发现了这个项目，可惜没能找到很好的联系方式能与您联系。
非常欣赏您在iPelago项目上的努力并且有着和您相近的价值观（关于社交媒体，话语权和个人空间），很希望能和您进一步的交流甚至共同开发。
我的联系方式 V UkhJVEpvaG4yMDE4 (Base64) 邮箱 Y2hlbnh1andhbmdAZ21haWwuY29t (Base64)

如果您对合作没有太多的兴趣或暂时希望独立完成这个项目开发，再次为冒昧的打扰表示歉意。无论如何我将于三日之内关闭此issue

John Wang

**Comment by ahui2016** [comment]
你好！已发gmail
